# Included from ctest after gtest discovery has registered every test.
# ARES_BINARY_DIR is set by the generated wrapper. Test names are read from
# --gtest_filter entries so both Ninja and Makefile discovery files work.
if(NOT ARES_BINARY_DIR)
    return()
endif()

file(GLOB _ares_all LIST_DIRECTORIES false "${ARES_BINARY_DIR}/*")
foreach(_ares_item IN LISTS _ares_all)
    get_filename_component(_ares_base "${_ares_item}" NAME)
    if(NOT _ares_base MATCHES "^ares_tests.*_tests\\.cmake$")
        continue()
    endif()
    file(READ "${_ares_item}" _ares_body)
    string(REGEX MATCHALL "--gtest_filter=[A-Za-z0-9_.]+" _ares_filters "${_ares_body}")
    foreach(_ares_filter IN LISTS _ares_filters)
        string(REGEX REPLACE "^--gtest_filter=" "" _ares_test "${_ares_filter}")
        set(_ares_labels "")
        if(_ares_test MATCHES
           "^(Application|ApplicationExit|TaskSupervisor|BootSequence|MissionExit|SimulatedSpacecraft|FdirScenario|SafeModeRecovery|ChaosCampaign|Recording|TaskRestart)\\.")
            list(APPEND _ares_labels integration)
        else()
            list(APPEND _ares_labels unit)
        endif()
        if(_ares_test MATCHES "^(Fault|Deadline|Fdir|SafeMode)")
            list(APPEND _ares_labels fault)
        endif()
        if(_ares_test MATCHES "^(Recovery|TaskRestart|Gps|SafeMode)")
            list(APPEND _ares_labels recovery)
        endif()
        if(_ares_test MATCHES "^(FlightRecorder|Recording)\\.")
            list(APPEND _ares_labels recorder)
        endif()
        if(_ares_test MATCHES "^Replay\\.")
            list(APPEND _ares_labels replay)
        endif()
        set_tests_properties("${_ares_test}" PROPERTIES LABELS "${_ares_labels}" TIMEOUT 60)
    endforeach()
endforeach()

set_tests_properties(ares_smoke PROPERTIES TIMEOUT 60 LABELS "smoke;integration")
